### ISSUE TITLE
Regression on Spring Data Elasticsearch

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#1492]
**Intro**
While Spring Data Elasticsearch worked fine with Spring Boot 2.5.x + Spring Native 0.10x
It stopped working in Spring Boot 2.6.x + 0.11x.

During Bootstrap we now get Reflection errors like "no suitable constructor found ..."

**Description**
I suspect a similiar regression like in https://github.com/spring-projects-experimental/spring-native/issues/1370,
where the Behavior of TypeHint changed.

And there is als a very similar issue to Spring Data Mongodb
https://github.com/spring-projects-experimental/spring-native/issues/1487

I already started adding Typehints one by one .. but this isn't ending:

@TypeHint(types = org.apache.logging.log4j.message.ParameterizedMessageFactory.class, access = {TypeAccess.DECLARED_CLASSES, TypeAccess.DECLARED_CONSTRUCTORS, TypeAccess.DECLARED_METHODS})

@TypeHint(types = org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.class, access = {TypeAccess.DECLARED_CLASSES, TypeAccess.DECLARED_CONSTRUCTORS, TypeAccess.DECLARED_METHODS})

**Example**
I created a simpler branch of the existing repo, that needs to build with the Maven Profile "docker-image-native"
This is missing the Typehints above to get the original errors.
https://github.com/goafabric/example-search-service/tree/native-image-regression

Build works .. bootstrap fails.

I suspect that the existing Typehints for SPring Data Elastic + Mongodb need to be reworked similar like #1370

**Comment by sdeleuze** [comment]
The repro seems not usable, I got compilation error when running `./build-native.sh`.

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.319 s
[INFO] Finished at: 2022-02-17T15:18:48+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project example-search-service-core: Compilation failure: Compilation failure: 
[ERROR] /home/seb/playground/example-search-service/example-search-service-core/src/main/java/org/goafabric/example/searchservice/logic/PersonMapper.java:[3,55] cannot find symbol
[ERROR]   symbol:   class PersonBo
[ERROR]   location: package org.goafabric.example.searchservice.persistence
[ERROR] /home/seb/playground/example-search-service/example-search-service-core/src/main/java/org/goafabric/example/searchservice/logic/PersonMapper.java:[11,16] cannot find symbol
```
Please fix it to allow me to reproduce the issue reported.

**Comment by goafabric** [comment]
@sdeleuze 
Thats very odd, because the build works inside github
https://github.com/goafabric/example-search-service/actions/runs/1833510776

Did you really checkout the branch "native-image-regression" ?
Because this looks like the develop .. which yes seems to be broken currently
